{% set version = "6.1.2" %}

package:
  name: pyface
  version: {{ version }}

source:
  fn: pyface-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/p/pyface/pyface-{{ version }}.tar.gz
  sha256: 7c2ac3d5cbec85e8504b3b0b63e9307be12c6d710b46bae372ce6562d41f4fbc

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python
  run:
    - python
    - traits
    - pyqt  # pyface requires pyqt 4 or 5, pyside or wxpython 3
    - pygments

test:
  imports:
    - pyface

about:
  home: http://docs.enthought.com/pyface/
  license: BSD 3-clause
  summary: pyface - traits-capable windowing framework

extra:
  recipe-maintainers:
    - grlee77
