{% set version = "7.4.1" %}

package:
  name: pyface
  version: {{ version }}

source:
  fn: pyface-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/p/pyface/pyface-{{ version }}.tar.gz
  sha256: 52dcf3679ca3e610a3ca7c4b9904a96c691688048db5d7e52af8e5019e47adb6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - traits
    - pyqt  # pyface requires pyqt 4 or 5, pyside or wxpython 3
    - pygments
    - importlib_resources
    - importlib_metadata

test:
  imports:
    - pyface

about:
  home: http://docs.enthought.com/pyface/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: pyface - traits-capable windowing framework

extra:
  recipe-maintainers:
    - grlee77
    - larsoner
