{% set version = "6.0.0" %}

package:
  name: pyface
  version: {{ version }}

source:
  fn: pyface-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/p/pyface/pyface-{{ version }}.tar.gz
  sha256: bf0552597a587452fcfa212f956c3a59931ba301cca6eeb144227466da456276

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pyqt  # pyface requires pyqt 4 or 5, pyside or wxpython 3
    - traits
    - pygments
  run:
    - python
    - traits
    - pyqt
    - pygments

test:
  imports:
    - pyface

about:
  home: http://docs.enthought.com/pyface/
  license: BSD 3-clause
  summary: pyface - traits-capable windowing framework

extra:
  recipe-maintainers:
    - grlee77
