{% set version = "7.0.1" %}

package:
  name: pyface
  version: {{ version }}

source:
  fn: pyface-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/p/pyface/pyface-{{ version }}.tar.gz
  sha256: 43943cc15889153b90191d9e1bd85e7a3709a6d57b6379220cb14017217fb999

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python
  run:
    - python
    - traits
    - pyqt  # pyface requires pyqt 4 or 5, pyside or wxpython 3
    - pygments

test:
  imports:
    - pyface

about:
  home: http://docs.enthought.com/pyface/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: pyface - traits-capable windowing framework

extra:
  recipe-maintainers:
    - grlee77
