{% set version = "7.4.0" %}

package:
  name: pyface
  version: {{ version }}

source:
  fn: pyface-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/p/pyface/pyface-{{ version }}.tar.gz
  sha256: afc0308fd74e60f5b187502bd892bf9e1b98f2100614ee3eeb2afdcaaecf6fab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - traits
    - pyqt  # pyface requires pyqt 4 or 5, pyside or wxpython 3
    - pygments
    - importlib_resources
    - importlib_metadata

test:
  imports:
    - pyface

about:
  home: http://docs.enthought.com/pyface/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: pyface - traits-capable windowing framework

extra:
  recipe-maintainers:
    - grlee77
