travis:
  secure:
    BINSTAR_TOKEN: bntdgQhTfy744f1e+9C+sKRW/auV5aXc7L6uInXTZOJgWJMwDo6Kw8P0Ypxok3Ck5n+W4mDhKPNN0GDIrjVuWcMIhO52jQwqmciFsEupbXZpJhvPLeUgdjGOCzhXbqlacm9DKBMvzw6HsfCl1RGSDX3lPgmWSab4BFUWOpWHRZ8ObmbgskPglzqJTYeV2RGJKNfAkFPL3mxZennafpXz8naFheQ6QmIF1Fmmm1nhh9Ea7gy/m3HZ901wdjG8wSOdokcreQSSLDPeMB+ck//I1WVU+VELbmQ/iq8TBdgsDbxL75GiQF4laINo5mGJQWjzvn0XNrawCoxCJfU1RJOW9vAiK8R/4umohqg4K30DkWTvP84jEiVokvvNwwlkIf1LQ7dsF9jQj1zX0XFr9siL3EYb+B9SKaz46R+KschlbI27NtJ3ehRllyjLdwjYKzzvDNAzKOYCZ1InlHsMoCjiF36lD86hF2WaCKnoKPiJRLVJZuZqz/BIl9dTl2K+ttQ42ZZW3XzNqY13bkij3br3740zga7qWZD2oxzsHsFa99gtgu2j7UsIEWdjNTxaFA9kP0m/30v6xVUkQuNWAZeepKf2SiCF8JWLpSyP1C5MJ2SvwX0i2+ESEgH/1fG68XDAWOys6tnu49FG6a0S34kMXLZvmvwqeNwNg48KNtbQXIE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
